# Run this script in WSL with the following command in the PowerShell Terminal: wsl python3 /mnt/r/Media/Music/GroovyTunes/Scripts/dj_set_manager.py

import os
import json
import shutil
import time
import numpy as np
import essentia
import essentia.standard as es
from mutagen.id3 import ID3, TCON, TBPM, TKEY, COMM, ID3NoHeaderError

essentia.log.warningActive = False
essentia.log.infoActive = False

# --- CONFIGURATION ---
# The location of the JSON file generated by Mood Detector
cache_file = r"c:\Work\Mood-Detector\music_library_cache.json"

# --- PHASE 1: GENRE REFINEMENT ---
# Model files are stored in the local models folder next to this script.
# Keep only discogs400 active for this phase.
embedding_model = "discogs-effnet-bs64-1.pb"
GENRE_MODEL_COMBOS = [
    {
        "name": "discogs400",
        "genre_model": "genre_discogs400-discogs-effnet-1.pb",
        "labels": "genre_discogs400-discogs-effnet-1.json",
    },
    # {
    #     "name": "electronic",
    #     "genre_model": "genre_electronic-discogs-effnet-1.pb",
    #     "labels": "genre_electronic-discogs-effnet-1.json",
    # },
    # {
    #     "name": "mtg_jamendo",
    #     "genre_model": "mtg_jamendo_genre-discogs-effnet-1.pb",
    #     "labels": "mtg_jamendo_genre-discogs-effnet-1.json",
    # },
]
active_genre_combo = "discogs400"
phase1_output_file = r"r:\Media\Music\GroovyTunes\genre_refinement_results.json"
phase1_save_every_tracks = 10
phase1_save_every_seconds = 30
phase4_cue_export_file = r"r:\Media\Music\GroovyTunes\phase4_mik_cues.json"
phase4_mik_export_search_root = None  # defaults to destination_folder when None
phase4_mik_sidecar_extensions = (".cue", ".txt", ".csv", ".xml")

model_dir = os.path.join(os.path.dirname(os.path.abspath(__file__)), "models")

# Optional source folder filter. Set to None to disable.
source_folder = r"R:\Media\Music\GroovyTunes\MP3"

# The destination folder where matching tracks will be copied
destination_folder = r"r:\Media\Music\GroovyTunes\2026-05-25_Selected"

# Allowed keys in Camelot notation
allowed_camelot_keys = ("7A", "8A", "9A", "10A", "11A")

# Camelot -> standard key mapping
camelot_to_standard = {
    "1A": "Ab minor", "1B": "B major",
    "2A": "Eb minor", "2B": "F# major",
    "3A": "Bb minor", "3B": "Db major",
    "4A": "F minor", "4B": "Ab major",
    "5A": "C minor", "5B": "Eb major",
    "6A": "G minor", "6B": "Bb major",
    "7A": "D minor", "7B": "F major",
    "8A": "A minor", "8B": "C major",
    "9A": "E minor", "9B": "G major",
    "10A": "B minor", "10B": "D major",
    "11A": "F# minor", "11B": "A major",
    "12A": "Db minor", "12B": "E major",
}

allowed_keys = {
    camelot_to_standard[key]
    for key in allowed_camelot_keys
    if key in camelot_to_standard
}

# Phase 2 favorite-style genre profile (replaces mood filtering)
phase2_preferred_genres = {
    "Techno",
    "Minimal Techno",
    "Tech Trance",
    "Tech House",
    "Deep Techno",
    "Minimal",
}
phase2_anchor_genres = {"Techno", "Minimal Techno", "Tech Trance"}
phase2_min_genre_percentage = 20.0
phase2_min_anchor_percentage = 30.0
phase2_min_matched_genres = 2

standard_to_camelot = {
    standard_key.lower(): camelot_key
    for camelot_key, standard_key in camelot_to_standard.items()
}

key_name_aliases = {
    "g# minor": "ab minor",
    "a# minor": "bb minor",
    "d# major": "eb major",
    "g# major": "ab major",
    "c# major": "db major",
    "d# minor": "eb minor",
    "a# major": "bb major",
    "gb major": "f# major",
    "gb minor": "f# minor",
}


def _format_duration(seconds):
    if seconds < 0:
        seconds = 0
    total_seconds = int(round(seconds))
    hours = total_seconds // 3600
    minutes = (total_seconds % 3600) // 60
    secs = total_seconds % 60
    return f"{hours:02d}:{minutes:02d}:{secs:02d}"


def _to_runtime_path(path):
    if not path:
        return path

    path = str(path)
    if os.name == 'nt':
        return path

    normalized = path.replace('\\', '/')
    if len(normalized) >= 2 and normalized[1] == ':':
        drive_letter = normalized[0].lower()
        tail = normalized[2:].lstrip('/')
        return f"/mnt/{drive_letter}/{tail}" if tail else f"/mnt/{drive_letter}"

    return path


def _model_path(filename):
    return _to_runtime_path(os.path.join(model_dir, filename))


def _to_windows_path(path):
    if not path:
        return path

    normalized = str(path).replace('/', '\\')
    if len(normalized) >= 7 and normalized.lower().startswith('\\mnt\\') and normalized[5].isalpha():
        drive_letter = normalized[5]
        tail = normalized[7:]
        return f"{drive_letter.upper()}:\\{tail}" if tail else f"{drive_letter.upper()}:\\"

    return normalized


def _normalize_genre_label(label):
    text = str(label or "").strip()
    return text.split("---", 1)[1] if text.startswith("Electronic---") else text


def _save_phase1_results(results_path, results):
    os.makedirs(os.path.dirname(results_path), exist_ok=True)
    temp_path = f"{results_path}.tmp"
    with open(temp_path, 'w', encoding='utf-8') as f:
        json.dump(results, f, ensure_ascii=False, indent=2)
    os.replace(temp_path, results_path)


def _save_json_file(output_path, payload):
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    temp_path = f"{output_path}.tmp"
    with open(temp_path, 'w', encoding='utf-8') as f:
        json.dump(payload, f, ensure_ascii=False, indent=2)
    os.replace(temp_path, output_path)


def _confirm_phase_run(phase_label):
    while True:
        answer = input(f"Run {phase_label}? [Y/n]: ").strip().lower()
        if answer in ("", "y", "yes"):
            return True
        if answer in ("n", "no"):
            return False
        print("Please answer Y or N.")


def _read_text_file_safe(filepath, max_chars=4000):
    try:
        with open(filepath, 'r', encoding='utf-8', errors='replace') as f:
            content = f.read(max_chars)
        return content
    except Exception:
        return ""


def _build_mik_sidecar_index(search_root):
    if not search_root or not os.path.isdir(search_root):
        return {}

    sidecar_index = {}
    for root, _, files in os.walk(search_root):
        for name in files:
            ext = os.path.splitext(name)[1].lower()
            if ext not in phase4_mik_sidecar_extensions:
                continue

            stem = os.path.splitext(name)[0].lower()
            sidecar_path = os.path.join(root, name)
            sidecar_index.setdefault(stem, []).append(sidecar_path)

    return sidecar_index


def _load_phase1_genre_lookup(results_path):
    if not os.path.exists(results_path):
        return {}

    try:
        with open(results_path, 'r', encoding='utf-8') as f:
            data = json.load(f)
    except Exception:
        return {}

    if not isinstance(data, list):
        return {}

    lookup = {}
    for entry in data:
        if not isinstance(entry, dict):
            continue
        entry_path = entry.get("path")
        if not entry_path:
            continue
        normalized_path = os.path.normcase(os.path.normpath(_to_runtime_path(entry_path)))
        lookup[normalized_path] = entry.get("genres", []) if isinstance(entry.get("genres"), list) else []

    return lookup


def _matches_favorite_genre_profile(genres):
    matched_genres = []
    anchor_match = False

    for genre_item in genres:
        if not isinstance(genre_item, dict):
            continue

        genre_name = str(genre_item.get("genre", "")).strip()
        percentage = float(genre_item.get("percentage", 0) or 0)

        if genre_name not in phase2_preferred_genres:
            continue
        if percentage < phase2_min_genre_percentage:
            continue

        matched_genres.append(genre_name)

        if genre_name in phase2_anchor_genres and percentage >= phase2_min_anchor_percentage:
            anchor_match = True

    return anchor_match and len(set(matched_genres)) >= phase2_min_matched_genres


def _normalize_key_name_for_lookup(raw_key):
    key_text = str(raw_key or "").strip().lower()
    if not key_text:
        return ""

    key_text = key_text.replace('♯', '#').replace('♭', 'b')
    key_text = key_text.replace('_', ' ').replace('-', ' ')
    key_text = ' '.join(key_text.split())

    mode = ""
    note = key_text

    if "major" in key_text:
        mode = "major"
        note = key_text.replace("major", "").strip()
    elif "minor" in key_text:
        mode = "minor"
        note = key_text.replace("minor", "").strip()
    elif key_text.endswith("maj"):
        mode = "major"
        note = key_text[:-3].strip()
    elif key_text.endswith("min"):
        mode = "minor"
        note = key_text[:-3].strip()
    elif key_text.endswith("m") and len(key_text) > 1:
        mode = "minor"
        note = key_text[:-1].strip()

    note = note.replace(" ", "")

    if mode and note:
        normalized = f"{note} {mode}"
    else:
        normalized = key_text

    return key_name_aliases.get(normalized, normalized)


def _extract_mik_cue_entries(tags):
    cue_entries = []

    for frame in tags.values():
        frame_id = getattr(frame, "FrameID", "")
        if frame_id != "TXXX":
            continue

        desc = str(getattr(frame, "desc", "")).strip()
        desc_lower = desc.lower()
        if not any(token in desc_lower for token in ("cue", "hot", "marker", "point")):
            continue

        text_values = getattr(frame, "text", [])
        value = " | ".join(str(v) for v in text_values)
        cue_entries.append({
            "frame": frame_id,
            "description": desc,
            "value": value,
        })

    return cue_entries


def _format_genre_tag_value(genres, fallback_genre):
    if isinstance(genres, list) and genres:
        parts = []
        for genre_item in genres:
            if not isinstance(genre_item, dict):
                continue
            genre_name = str(genre_item.get("genre", "")).strip()
            if not genre_name:
                continue
            percentage = int(round(float(genre_item.get("percentage", 0) or 0)))
            parts.append(f"{genre_name} ({percentage}%)")

        if parts:
            return ", ".join(parts)

    return str(fallback_genre or "").strip()


def _to_camelot_key(standard_key):
    raw_key = str(standard_key or "").strip()
    if not raw_key:
        return ""

    raw_upper = raw_key.upper()
    if len(raw_upper) >= 2 and raw_upper[-1] in ("A", "B") and raw_upper[:-1].isdigit():
        return f"{int(raw_upper[:-1]):02d}{raw_upper[-1]}"

    normalized_key = _normalize_key_name_for_lookup(raw_key)
    camelot = standard_to_camelot.get(normalized_key, raw_key.strip())

    camelot_upper = camelot.upper()
    if len(camelot_upper) >= 2 and camelot_upper[-1] in ("A", "B") and camelot_upper[:-1].isdigit():
        return f"{int(camelot_upper[:-1]):02d}{camelot_upper[-1]}"

    return camelot_upper


def _load_genre_labels(labels_path):
    with open(labels_path, 'r', encoding='utf-8') as f:
        labels_data = json.load(f)
    return labels_data.get('classes', labels_data) if isinstance(labels_data, dict) else labels_data


def _build_embedding_model_runner():
    if hasattr(es, "TensorflowPredictEffnetDiscogs"):
        return es.TensorflowPredictEffnetDiscogs(
            graphFilename=_model_path(embedding_model), output="PartitionedCall:1")

    if hasattr(es, "TensorflowPredict"):
        print("Essentia compatibility mode: using TensorflowPredict fallback for embeddings.")
        return es.TensorflowPredict(
            graphFilename=_model_path(embedding_model),
            output="PartitionedCall:1")

    raise AttributeError(
        "Your Essentia build does not expose TensorFlow prediction algorithms. "
        "Install an Essentia package with TensorFlow support."
    )


def _build_genre_classifier_runner(genre_model_filename):
    graph_filename = _model_path(genre_model_filename)
    io_candidates = [
        ("serving_default_model_Placeholder", "PartitionedCall:0"),
        ("model/Placeholder", "model/Softmax"),
        ("model/Placeholder", "model/Sigmoid"),
    ]

    if hasattr(es, "TensorflowPredict2D"):
        last_error = None
        for input_node, output_node in io_candidates:
            try:
                if input_node != "serving_default_model_Placeholder":
                    print("Essentia compatibility mode: using legacy TensorFlow node names for genre model.")
                return es.TensorflowPredict2D(
                    graphFilename=graph_filename,
                    input=input_node,
                    output=output_node)
            except Exception as ex:
                last_error = ex
        raise last_error

    if hasattr(es, "TensorflowPredict"):
        print("Essentia compatibility mode: using TensorflowPredict fallback for genre model.")
        last_error = None
        for input_node, output_node in io_candidates:
            try:
                if input_node != "serving_default_model_Placeholder":
                    print("Essentia compatibility mode: using legacy TensorFlow node names for genre model.")
                return es.TensorflowPredict(
                    graphFilename=graph_filename,
                    input=input_node,
                    output=output_node)
            except Exception as ex:
                last_error = ex
        raise last_error

    raise AttributeError(
        "Your Essentia build does not expose TensorFlow prediction algorithms. "
        "Install an Essentia package with TensorFlow support."
    )


def _build_genre_model_runner(combo):
    embed_model = _build_embedding_model_runner()
    genre_model = _build_genre_classifier_runner(combo['genre_model'])
    labels = _load_genre_labels(_model_path(combo['labels']))
    return embed_model, genre_model, labels


def write_mp3_tags(tracks_for_tagging):
    mp3_tracks = [track for track in tracks_for_tagging if track['dest_path'].lower().endswith('.mp3')]
    total_mp3 = len(mp3_tracks)

    print(f"Phase 3: Writing tags for {total_mp3} MP3 tracks...")
    if total_mp3 == 0:
        print("No MP3 tracks found for tagging.")
        return

    last_progress_update = time.time()

    for index, track in enumerate(mp3_tracks, start=1):
        dest_path = _to_runtime_path(track['dest_path'])
        mood = str(track.get('mood', '')).strip()
        tempo = float(track.get('tempo', 0) or 0)
        key = str(track.get('key', '')).strip()
        energy = float(track.get('energy', 0) or 0)
        genres = track.get('genres', [])

        dominant_genre = mood
        if isinstance(genres, list) and genres:
            first_item = genres[0]
            if isinstance(first_item, dict):
                dominant_genre = str(first_item.get('genre', dominant_genre)).strip() or dominant_genre

        genre_tag_value = _format_genre_tag_value(genres, dominant_genre)
        camelot_key = _to_camelot_key(key)
        comment_value = f"Energy {energy * 10:.1f}"

        try:
            try:
                tags = ID3(dest_path)
            except ID3NoHeaderError:
                tags = ID3()

            tags.delall('TCON')
            tags.delall('TBPM')
            tags.delall('TKEY')
            tags.delall('COMM')

            tags.add(TCON(encoding=3, text=[genre_tag_value]))
            tags.add(TBPM(encoding=3, text=[str(int(round(tempo)))]))
            tags.add(TKEY(encoding=3, text=[key]))
            tags.add(COMM(encoding=3, lang='eng', desc='', text=[comment_value]))

            tags.save(dest_path, v2_version=3)
        except Exception as ex:
            print(f"Tagging failed: {dest_path} ({ex})")

        now = time.time()
        should_update_progress = (now - last_progress_update) >= 1.0 or index == total_mp3
        if should_update_progress:
            progress_percent = (index / total_mp3) * 100
            print(f"Tagging: {progress_percent:.1f}%")
            last_progress_update = now

    print("Finished writing MP3 tags.")


def apply_mik_key_updates(tracks_for_tagging):
    mp3_tracks = [track for track in tracks_for_tagging if track['dest_path'].lower().endswith('.mp3')]
    total_mp3 = len(mp3_tracks)

    print(f"\nPhase 4: Mixed In Key sync for {total_mp3} MP3 tracks...")
    if total_mp3 == 0:
        print("No MP3 tracks found for Phase 4.")
        return

    print("Before continuing, do this in Mixed In Key 11:")
    print("1) Load the filtered tracks from the destination folder.")
    print("2) Analyze all tracks.")
    print("3) In Settings, configure:")
    print('   - Check "Update common tags"')
    print('   - Set "Only write the key"')
    print('   - Select "Overwrite the comments"')
    print('   - Check "Add a zero to single-digit Camelot numbers"')
    print('   - Check "Update custom \'Initial Key\'"')
    print('   - Check "Update tempo tags"')
    print('   - Check "Update custom \"Energy Level\" tag"')
    print("4) Run Mixed In Key analysis and wait until tags are written.")

    while True:
        user_input = input("Type READY when MIK has finished (or SKIP to skip Phase 4): ").strip().upper()
        if user_input == "READY":
            break
        if user_input == "SKIP":
            print("Phase 4 skipped by user.")
            return
        print("Please type READY or SKIP.")

    cue_export_path = _to_runtime_path(phase4_cue_export_file)
    sidecar_search_root = _to_runtime_path(phase4_mik_export_search_root or destination_folder)
    sidecar_index = _build_mik_sidecar_index(sidecar_search_root)

    cue_export_entries = []
    cue_tracks_with_entries = 0
    cue_tracks_with_sidecars = 0
    last_progress_update = time.time()

    for index, track in enumerate(mp3_tracks, start=1):
        dest_path = _to_runtime_path(track['dest_path'])
        energy = float(track.get('energy', 0) or 0)

        try:
            tags = ID3(dest_path)

            key_frames = tags.getall('TKEY')
            bpm_frames = tags.getall('TBPM')

            mik_key_raw = ""
            if key_frames and key_frames[0].text:
                mik_key_raw = str(key_frames[0].text[0]).strip()

            if not mik_key_raw:
                raise ValueError("Missing TKEY after MIK analysis")

            camelot_key = _to_camelot_key(mik_key_raw)

            bpm_value = 0.0
            if bpm_frames and bpm_frames[0].text:
                bpm_text = str(bpm_frames[0].text[0]).strip().replace(',', '.')
                bpm_value = float(bpm_text)
            if bpm_value <= 0:
                bpm_value = float(track.get('tempo', 0) or 0)

            comment_value = f"{camelot_key} - {bpm_value:.1f} BPM - Energy {energy * 10:.1f}"

            cue_entries = _extract_mik_cue_entries(tags)
            cue_sidecars = []

            stem = os.path.splitext(os.path.basename(dest_path))[0].lower()
            matching_sidecars = sidecar_index.get(stem, [])
            if matching_sidecars:
                cue_tracks_with_sidecars += 1
                for sidecar_path in matching_sidecars:
                    cue_sidecars.append({
                        "path": _to_windows_path(sidecar_path),
                        "preview": _read_text_file_safe(sidecar_path),
                    })

            if cue_entries or cue_sidecars:
                cue_tracks_with_entries += 1

            cue_export_entries.append({
                "filename": os.path.basename(dest_path),
                "path": _to_windows_path(dest_path),
                "camelot_key": camelot_key,
                "bpm": round(bpm_value, 1),
                "cue_entries": cue_entries,
                "cue_sidecars": cue_sidecars,
            })

            tags.delall('TKEY')
            tags.delall('COMM')
            tags.add(TKEY(encoding=3, text=[camelot_key]))
            tags.add(COMM(encoding=3, lang='eng', desc='', text=[comment_value]))
            tags.save(dest_path, v2_version=3)

        except Exception as ex:
            print(f"Phase 4 update failed: {dest_path} ({ex})")

        now = time.time()
        should_update_progress = (now - last_progress_update) >= 1.0 or index == total_mp3
        if should_update_progress:
            progress_percent = (index / total_mp3) * 100
            print(f"Phase 4 sync: {progress_percent:.1f}%")
            last_progress_update = now

    _save_json_file(cue_export_path, cue_export_entries)
    print(f"Finished Phase 4 Mixed In Key sync.")
    print(f"Phase 4 cue export saved: {phase4_cue_export_file} (tracks with cues: {cue_tracks_with_entries}/{len(cue_export_entries)}, sidecar matches: {cue_tracks_with_sidecars})")
    if cue_tracks_with_entries == 0:
        print("No cue metadata detected in ID3 tags.")
        print("If you used MIK 'Export cue points', check the exported files in the destination folder tree or set phase4_mik_export_search_root.")


def refine_genres(_cache_data=None):
    print("\nPhase 1: Extracting genres with Essentia (discogs400)...")
    print("Phase 1/5: Initializing...")

    source_folder_runtime = _to_runtime_path(source_folder) if source_folder else None
    output_runtime_path = _to_runtime_path(phase1_output_file)

    if not source_folder_runtime or not os.path.isdir(source_folder_runtime):
        print(f"Phase 1 aborted: source folder not found: {source_folder}")
        return []

    print("Phase 1/5: Loading existing output JSON...")
    existing_results = []
    existing_track_paths = set()
    if os.path.exists(output_runtime_path):
        try:
            with open(output_runtime_path, 'r', encoding='utf-8') as f:
                existing_results = json.load(f)
            if not isinstance(existing_results, list):
                print(f"Phase 1 aborted: existing output is not a JSON array: {phase1_output_file}")
                return []

            existing_track_paths = {
                os.path.normcase(os.path.normpath(_to_runtime_path(entry.get('path', ''))))
                for entry in existing_results
                if isinstance(entry, dict) and entry.get('path')
            }
        except Exception as ex:
            print(f"Phase 1 aborted: failed to parse existing output JSON ({ex}).")
            print("Existing file was not modified.")
            return []

    print("Phase 1/5: Listing MP3 files in source folder...")
    all_source_files = []
    for root, _, files in os.walk(source_folder_runtime):
        for filename in files:
            if filename.lower().endswith('.mp3'):
                all_source_files.append(os.path.join(root, filename))

    candidates = []
    for runtime_file_path in all_source_files:
        normalized_runtime_path = os.path.normcase(os.path.normpath(runtime_file_path))
        if normalized_runtime_path in existing_track_paths:
            continue
        candidates.append((runtime_file_path, normalized_runtime_path))

    total_source = len(all_source_files)
    total_to_process = len(candidates)
    print(f"Found {total_source} MP3 files. New files to analyze: {total_to_process}. Skipping {len(existing_track_paths)} already in JSON.")

    if total_to_process == 0:
        print(f"No new tracks to analyze. Existing output kept: {phase1_output_file}")
        return existing_results

    print("Phase 1/5: Loading Essentia models...")
    try:
        model_sets = []
        for combo in GENRE_MODEL_COMBOS:
            embed_model, genre_model, labels = _build_genre_model_runner(combo)
            model_sets.append({
                "name": combo["name"],
                "embed_model": embed_model,
                "genre_model": genre_model,
                "labels": labels,
            })
    except FileNotFoundError as ex:
        print(f"Model file not found: {ex}\nSkipping Phase 1.")
        return existing_results
    except Exception as ex:
        print(f"Failed to load Essentia models: {ex}\nSkipping Phase 1.")
        return existing_results

    active_set = next((model_set for model_set in model_sets if model_set["name"] == active_genre_combo), model_sets[0])
    print(f"Using model set: {active_set['name']}")

    print("Phase 1/5: Running genre predictions...")
    results = list(existing_results)
    analyzed_count = 0
    saved_count = 0
    start_time = time.time()
    last_save_time = time.time()

    for index, (runtime_file_path, normalized_runtime_path) in enumerate(candidates, start=1):
        try:
            audio = es.MonoLoader(filename=runtime_file_path, sampleRate=16000, resampleQuality=4)()
            embeddings = active_set["embed_model"](audio)
            predictions = active_set["genre_model"](embeddings)
            avg_predictions = np.mean(predictions, axis=0)
            sorted_indices = np.argsort(avg_predictions)[::-1]

            genres = []
            for i in sorted_indices:
                raw_label = str(active_set["labels"][i])
                percentage = round(float(avg_predictions[i]) * 100, 2)
                if not raw_label.startswith("Electronic---"):
                    continue
                if percentage <= 20:
                    continue
                genres.append({
                    "genre": _normalize_genre_label(raw_label),
                    "percentage": percentage,
                })

            windows_path = _to_windows_path(runtime_file_path)
            results.append({
                "filename": os.path.basename(runtime_file_path),
                "path": windows_path,
                "genres": genres,
            })
            existing_track_paths.add(normalized_runtime_path)
            analyzed_count += 1

            elapsed = time.time() - start_time
            average_per_file = elapsed / index
            remaining_files = total_to_process - index
            eta_seconds = average_per_file * remaining_files
            progress_percent = (index / total_to_process) * 100
            print(f"Phase 1: {progress_percent:.1f}% | ETA: {_format_duration(eta_seconds)} | {os.path.basename(runtime_file_path)}")

            now = time.time()
            if (index % phase1_save_every_tracks == 0) or ((now - last_save_time) >= phase1_save_every_seconds) or index == total_to_process:
                print("Phase 1/5: Saving progress...")
                _save_phase1_results(output_runtime_path, results)
                saved_count += 1
                last_save_time = now

        except Exception as ex:
            print(f"Phase 1 failed for {os.path.basename(runtime_file_path)}: {ex}")

    print("Phase 1/5: Finalizing output JSON...")
    _save_phase1_results(output_runtime_path, results)
    print(f"\nPhase 1 complete. Analyzed {analyzed_count} new tracks.")
    print(f"Output kept and updated at: {phase1_output_file} (periodic saves: {saved_count})")
    return results


def filter_and_copy(cache_data, run_phase3=True, run_phase4=True):
    # Create the destination folder if it doesn't already exist
    destination_folder_runtime = _to_runtime_path(destination_folder)
    os.makedirs(destination_folder_runtime, exist_ok=True)

    source_folder_runtime = _to_runtime_path(source_folder) if source_folder else None
    source_folder_normalized = os.path.normcase(os.path.normpath(source_folder_runtime)) if source_folder_runtime else None
    phase1_genres_lookup = _load_phase1_genre_lookup(_to_runtime_path(phase1_output_file))

    print("Phase 2: Filtering tracks...")
    print(f"Phase 2 genre profiles loaded: {len(phase1_genres_lookup)}")
    tracks_to_copy = []
    tracks_for_tagging = []
    seen_filenames = set()

    for track in cache_data:
        mood = track.get('mood', '')
        tempo = track.get('tempo', 0)
        energy = track.get('energy', 0)
        key = track.get('key', '')
        file_path = track.get('path', '')
        runtime_file_path = _to_runtime_path(file_path)

        if source_folder_normalized:
            file_path_normalized = os.path.normcase(os.path.normpath(runtime_file_path))
            if not file_path_normalized.startswith(source_folder_normalized):
                continue

        # Phase 2 copies only MP3 files
        if not str(file_path).lower().endswith('.mp3'):
            continue

        normalized_runtime_path = os.path.normcase(os.path.normpath(runtime_file_path))
        track_genres = phase1_genres_lookup.get(normalized_runtime_path, [])

        bpm_match = 120 <= tempo <= 128
        genre_match = _matches_favorite_genre_profile(track_genres)
        energy_match = 0.5 <= energy <= 0.79  # Translates to the 5-7 range
        key_match = True  # Disabled: key estimation is currently unreliable

        if not (bpm_match and genre_match and energy_match and key_match):
            continue

        if not os.path.exists(runtime_file_path):
            print(f"File not found on disk, skipping: {runtime_file_path}")
            continue

        filename = os.path.basename(runtime_file_path)
        filename_normalized = os.path.normcase(filename)
        if filename_normalized in seen_filenames:
            continue

        seen_filenames.add(filename_normalized)
        dest_path = os.path.join(destination_folder_runtime, filename)
        dominant_genre = mood
        if track_genres:
            dominant_genre = str(track_genres[0].get('genre', dominant_genre)).strip() or dominant_genre

        track_for_tagging = {
            'dest_path': dest_path,
            'mood': dominant_genre,
            'tempo': tempo,
            'energy': energy,
            'key': key,
            'genres': track_genres,
        }

        tracks_for_tagging.append(track_for_tagging)

        # Do not copy if a file with the same filename already exists in destination
        if os.path.exists(dest_path):
            continue

        tracks_to_copy.append((runtime_file_path, dest_path))

    total_to_copy = len(tracks_to_copy)
    print(f"Tracks to copy: {total_to_copy}")

    if total_to_copy > 0:
        print("Copying files...")
        start_time = time.time()
        copied_count = 0

        for file_path, dest_path in tracks_to_copy:
            shutil.copy2(file_path, dest_path)
            copied_count += 1

            elapsed = time.time() - start_time
            average_per_file = elapsed / copied_count
            remaining_files = total_to_copy - copied_count
            eta_seconds = average_per_file * remaining_files
            progress_percent = (copied_count / total_to_copy) * 100

            print(f"{progress_percent:.1f}% | ETA: {_format_duration(eta_seconds)}")

        print(f"\nFinished! Successfully matched and copied {copied_count} tracks.")
    else:
        print("\nFinished! Successfully matched and copied 0 tracks.")

    if run_phase3:
        write_mp3_tags(tracks_for_tagging)
    else:
        print("Phase 3 skipped by user.")

    if run_phase4:
        apply_mik_key_updates(tracks_for_tagging)
        print("\nFinished Phase 4. Next: import tracks into Rekordbox for Phase 5.")
    else:
        print("Phase 4 skipped by user.")


if __name__ == "__main__":
    run_phase1 = _confirm_phase_run("Phase 1 (Genre extraction)")
    run_phase2 = _confirm_phase_run("Phase 2 (Filtering and copy)")
    run_phase3 = _confirm_phase_run("Phase 3 (ID3 write)")
    run_phase4 = _confirm_phase_run("Phase 4 (Mixed In Key sync)")

    if run_phase1:
        refine_genres()
    else:
        print("Phase 1 skipped by user.")

    if run_phase2:
        cache_file_runtime = _to_runtime_path(cache_file)
        print("Loading Mood Detector data...")
        try:
            with open(cache_file_runtime, 'r', encoding='utf-8') as f:
                cache_data = json.load(f)
        except FileNotFoundError:
            print(f"Could not find {cache_file_runtime}. Please check the path and try again.")
            exit(1)

        filter_and_copy(cache_data, run_phase3=run_phase3, run_phase4=run_phase4)
    else:
        print("Phase 2 skipped by user.")
        if run_phase3:
            print("Phase 3 requires Phase 2 output and was not run.")
        if run_phase4:
            print("Phase 4 requires Phase 2 output and was not run.")
